In [1]:
import numpy as np

In [2]:
a_matrix = np.matrix([[1, 2], [3, 4]])
print(a_matrix)

[[1 2]
 [3 4]]


In [3]:
a_matrix[1, 0] = 10
print(a_matrix)

[[ 1  2]
 [10  4]]


In [4]:
a_matrix[0] = [6, 3]
print(a_matrix)

[[ 6  3]
 [10  4]]


In [5]:
print(np.sort(a_matrix))

[[ 3  6]
 [ 4 10]]


In [6]:
a_matrix = np.matrix([[1, 2], [3, 4]])
print(a_matrix)

[[1 2]
 [3 4]]


In [7]:
a_matrix = np.matrix([[1, 2], [3, 4]])
print(a_matrix.T)

[[1 3]
 [2 4]]


In [9]:
a_matrix = np.matrix([[1, 2], [3, 4]])
print(a_matrix.flatten())

[[1 2 3 4]]


In [10]:
print(np.add(a_matrix, a_matrix))

[[2 4]
 [6 8]]


In [11]:
print(np.matmul(a_matrix, a_matrix))

[[ 7 10]
 [15 22]]
