In [1]:
import numpy as np

In [2]:
an_array = np.arange(0, 11)
print(an_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
first_element = an_array[0]
print(first_element)
last_element = an_array[10]
print(last_element)

0
10


In [5]:
first_five = an_array[:5]
print(first_five)

[0 1 2 3 4]


In [6]:
last_five = an_array[6::2]
print(last_five)

[ 6  8 10]


In [7]:
first_five_reverse = an_array[4::-1]
print(first_five_reverse)

[4 3 2 1 0]


In [8]:
final_two = an_array[-2:]
print(final_two)

[ 9 10]


In [9]:
print(an_array.size)

11


In [10]:
print(np.amax(an_array))

10
