In [1]:
import numpy as np

In [2]:
an_array = np.arange(0, 6)
print(an_array)

[0 1 2 3 4 5]


In [3]:
an_array[0] = 10
print(an_array)

[10  1  2  3  4  5]


In [4]:
an_array = np.arange(0, 6)
print(np.append(an_array, [6, 7]))


[0 1 2 3 4 5 6 7]


In [5]:
print(np.insert(an_array, 0, [10, 14]))

[10 14  0  1  2  3  4  5]


In [6]:
print(np.delete(an_array, 3))

[0 1 2 4 5]


In [7]:
print(an_array * 2)

[ 0  2  4  6  8 10]


In [9]:
another_array = np.array([3, 6, 21, 9, 10, 2])
print(-np.sort(-another_array))

[21 10  9  6  3  2]
