In [1]:
import numpy as np

In [4]:
student_grades = np.array([56, 78, 98, 90, 58, 64, 72, 93, 51, 67])
print(student_grades)

[56 78 98 90 58 64 72 93 51 67]


In [5]:
class_average = np.average(student_grades)
print(class_average)

72.7


In [6]:
highest_grade = np.amax(student_grades)
print(highest_grade)

lowest_grade = np.amin(student_grades)
print(lowest_grade)

98
51


In [7]:
print(np.argmax(student_grades))
print(np.argmin(student_grades))

2
8


In [9]:
print(np.sort(student_grades))
print(-np.sort(-student_grades))

[51 56 58 64 67 72 78 90 93 98]
[98 93 90 78 72 67 64 58 56 51]


In [11]:
increased_grades = student_grades * 1.1
print(increased_grades)

[ 61.6  85.8 107.8  99.   63.8  70.4  79.2 102.3  56.1  73.7]


In [12]:
increased_grades = student_grades + 10
print(increased_grades)

[ 66  88 108 100  68  74  82 103  61  77]


In [15]:
print(np.add(student_grades, np.ones(10)))

[57. 79. 99. 91. 59. 65. 73. 94. 52. 68.]


In [16]:
print(np.add(student_grades, np.array([1,2,3,4,5,6,7,8,9,10])))

[ 57  80 101  94  63  70  79 101  60  77]
